// <auto-generated />
using System;
using IOC.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230111115529_ConnectAvailabilityAndUser")]
    partial class ConnectAvailabilityAndUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IOC.Models.Availability", b =>
                {
                    b.Property<int>("IdAvailability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvailability"));

                    b.Property<int?>("IdParticipant")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdAvailability");

                    b.HasIndex("IdUser");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("IOC.Models.User", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MailAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("IDUser")
                        .HasName("PK_User");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("IOC.Models.UserRefreshToken", b =>
                {
                    b.Property<int>("IDUserRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUserRefreshToken"));

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.HasKey("IDUserRefreshToken")
                        .HasName("PK_UserRefreshToken");

                    b.HasIndex("IDUser");

                    b.ToTable("UserRefreshToken", (string)null);
                });

            modelBuilder.Entity("IOC.Models.Availability", b =>
                {
                    b.HasOne("IOC.Models.User", "User")
                        .WithMany("Availabilities")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Availabilities_User_IdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOC.Models.UserRefreshToken", b =>
                {
                    b.HasOne("IOC.Models.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("IDUser")
                        .IsRequired()
                        .HasConstraintName("FK_UserRefreshToken_User_IDUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOC.Models.User", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
